"""create tables

Revision ID: 8bd0f7257b55
Revises: 
Create Date: 2025-06-23 01:30:20.747956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd0f7257b55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authcodes',
    sa.Column('authcode_id', sa.String(length=36), nullable=False, comment='認証コードID'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='コード'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('expire_datetime', sa.DateTime(), nullable=False, comment='有効期限'),
    sa.Column('delete_flag', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('create_datetime', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('update_datetime', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('authcode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authcodes')
    # ### end Alembic commands ###
